[build]
  publish = "resources"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/open_contest.html"
  to = "/templates/open_contest.html"
  status = 200

[[redirects]]
  from = "/login.html"
  to = "/templates/login.html"
  status = 200

[[redirects]]
  from = "/register.html"
  to = "/templates/register.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200