[build]
  publish = "resources"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/group"
  to = "/templates/group.html"
  status = 200

[[redirects]]
  from = "/board"
  to = "/templates/board.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/templates/search.html"
  status = 200

[[redirects]]
  from = "/user"
  to = "/templates/user.html"
  status = 200

[[redirects]]
  from = "/user/contest"
  to = "/templates/my_contest.html"
  status = 200

[[redirects]]
  from = "/user/problem"
  to = "/templates/my_problem.html"
  status = 200

[[redirects]]
  from = "/modify"
  to = "/templates/edit_userInfo.html"
  status = 200

[[redirects]]
  from = "/password/change"
  to = "/templates/change_password.html"
  status = 200

[[redirects]]
  from = "/user/management"
  to = "/templates/user_list.html"
  status = 200

[[redirects]]
  from = "/contest"
  to = "/templates/contest_list.html"
  status = 200

[[redirects]]
  from = "/problem"
  to = "/templates/problem_list.html"
  status = 200

[[redirects]]
  from = "/problem/add"
  to = "/templates/make_problem.html"
  status = 200

[[redirects]]
  from = "/contest/open"
  to = "/templates/make_contest.html"
  status = 200

[[redirects]]
  from = "/contest/*"
  to = "/templates/open_contest.html"
  status = 200

[[redirects]]
  from = "/problem/*"
  to = "/templates/open_problem.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/templates/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/templates/register.html"
  status = 200

[[redirects]]
  from = "/index"
  to = "/templates/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200