[build]
  publish = "resources"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/test"
  to = "/templates/test.html"
  status = 200

[[redirects]]
  from = "/contest_list"
  to = "/templates/contest_list.html"
  status = 200

[[redirects]]
  from = "/problem_list"
  to = "/templates/problem_list.html"
  status = 200

[[redirects]]
  from = "/open_contest"
  to = "/templates/open_contest.html"
  status = 200

[[redirects]]
  from = "/open_problem"
  to = "/templates/open_problem.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/templates/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/templates/register.html"
  status = 200

[[redirects]]
  from = "/index"
  to = "/templates/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200